[package]
name = "linter_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linter_api = { path = "../linter_api" }
bincode = "1.3.3"
